* Magic I Like
  These are examples of magic systems or spells I've seen in books or
  shows that I like.

** Medusa from Soul Eater's "Vector Plate" spell
   "Anything standing on top of one of my vector plates is propelled
   in the direction of the arrow."

   Episode 19 starting at about 17:40.
   http://www.animefreak.tv/watch/soul-eater-episode-19-english-dubbed-online-free#English

** Terry Pratchett's "Conservation of Energy" magic system
   You need to expand as much energy preparing a spell as that spell
   would use upon being cast.

** Terry Pratchett's witch magic
   Unlike wizards which try to store lots of magic inside themselves
   and then use it all at once, witches just try to move energy
   around.

   The example was holding two glasses of water at room temperature
   and moving the heat from one to the other so that the water in one
   boils and the one in the other freezes.  It's the same principle,
   but you can do this using the Sun as a source of heat..

** Sergei Lukyanenko's magicians-as-magic-black-holes idea
   In the Night Watch books, magicians are the only living being that
   don't produce magic.  Instead, they are sort of like holes in
   space-time that absorb magic.  Additionally, the stronger the
   magician, the more magic they can draw from around themselves;
   "absolute" magicians can actually convert reality into magic.

** Jura from Fairy Tail's "one spell" approach to magic
   Jura is a wizard who only knows one spell: lift rocks out of the
   ground and do something with them.  He gets a ridiculous amount of
   traction of this.

   Episode 160 starting at about 13:00.
   http://fairytailhq.tv/fairy-tail-episode-160/

** Mystigan from Fairy Tail's "launch spells from objects" approach to magic
   Mystigan draws magic circles on objects and landmarks while moving
   and sets off the spells later.

   Episode 160 starting at about 13:00.
   http://fairytailhq.tv/fairy-tail-episode-160/


* Old
** Sorcery
   The Sorcerer's Spells (see Smullyan's "Satan, Cantor, and Infinity")
   are programatic ways of effecting nature.

*** Promethean Magic
*** Rock Magic
*** Robotics
*** Displacement Magic
** Vancian Spells
   Vancian spells are magics that have fixed, well defined effects, and
   that have to be learned, acquired, or otherwise prepared.  I.e. a
   vancian spell is a one-shot spell, and you have to load more shots
   of it to be able to use it again.

*** Death Ray
*** Dvorak's Heresy
*** Colemak Madness
